{
   "broker" : {
      "default" : null
   },
   "connection" : {
      "default" : {
         "ethernet" : {
            "data_buffer" : 10100,
            "ip" : "",
            "port" : 5051
         }
      }
   },
   "connector" : {
      "default" : {
         "ip" : "127.0.0.1",
         "port" : 50000
      }
   },
   "general" : {
      "capabilities" : [ "inspection" ],
      "description" : "Generic Inspection",
      "vendor" : "Autodesk"
   }
}

